{{- if .Values.deployment.scaler.enabled -}}
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "deployment.fullname" . }}-autoscaler
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "deployment.labels" . | indent 6 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "deployment.fullname" . }}
  minReplicas: {{ .Values.deployment.scaler.minReplicas }}
  maxReplicas: {{ .Values.deployment.scaler.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: memory
        target:
          type: AverageValue
          averageValue: {{ .Values.deployment.scaler.avgMem }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.deployment.scaler.avgCPU }}
{{- end }}