image:
  repository: "868027517775.dkr.ecr.us-west-2.amazonaws.com/websocket-logger"
  tag: "v0.0.1"
  imagePullPolicy: IfNotPresent

deployment:
  replicas: 1
  logClient: true
  logServer: false
  annotations: |
    'consul.hashicorp.com/connect-inject': 'true'
    'consul.hashicorp.com/connect-service-upstreams': 'ksmcc3-ws:9944'
  upstream:
    uri: "localhost"
    port: 9944
  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  scaler:
    enabled: true
    minReplicas: 1
    maxReplicas: 10
    avgCPU: 50
    avgMem: 100Mi